# Generated by Django 2.0.2 on 2018-02-02 14:23

import random
from django.db import migrations

def insert_values(apps, schema_editor):
    Int = apps.get_model('app', 'Int')
    for i in range(10000):
        n = random.randrange(0, 9999)
        Int(value=n).save()
    

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_values)
    ]
