# Generated by Django 2.0.2 on 2018-02-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180202_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='int',
            name='value',
            field=models.IntegerField(),
        ),
    ]
